name: flu2
description: SuwaDerm - Skin Disease Identification and Support Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 📷 Image capture    
  image_picker: ^1.2.1

  # 🖼 Image processing
  image: ^4.7.2

  # 🧠 TensorFlow Lite model
  tflite_flutter: ^0.12.1

  # 🌐 Open external links
  url_launcher: ^6.3.0

  # ✨ Fonts
  google_fonts: ^6.2.1

  # 🎬 Animations
  lottie: ^3.1.0

  # 💾 Local storage
  shared_preferences: ^2.3.0

  # 🔥 Firebase
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/skin_disease_model_91class.tflite
    - assets/labels.txt
    - assets/icon.png   # ✅ ADD THIS

# 🎨 APP ICON CONFIG
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4