// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfe-9qw00EgldtgSh2-c1GGUWs4Vz1E1U',
    appId: '1:947319131768:web:7773ec732951c6cdb3678d',
    messagingSenderId: '947319131768',
    projectId: 'suwaderm',
    authDomain: 'suwaderm.firebaseapp.com',
    storageBucket: 'suwaderm.firebasestorage.app',
    measurementId: 'G-TEK29JJ6LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMOTzX90FiDeqI_kgL79z4MWb2Ojk1bAk',
    appId: '1:947319131768:android:8fdddfd250f9b361b3678d',
    messagingSenderId: '947319131768',
    projectId: 'suwaderm',
    storageBucket: 'suwaderm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd3Lv2O5tNu1oCySmcIJTkWTb9LEMtNdA',
    appId: '1:947319131768:ios:ec2ecb775d46f47ab3678d',
    messagingSenderId: '947319131768',
    projectId: 'suwaderm',
    storageBucket: 'suwaderm.firebasestorage.app',
    iosBundleId: 'com.example.flu2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd3Lv2O5tNu1oCySmcIJTkWTb9LEMtNdA',
    appId: '1:947319131768:ios:ec2ecb775d46f47ab3678d',
    messagingSenderId: '947319131768',
    projectId: 'suwaderm',
    storageBucket: 'suwaderm.firebasestorage.app',
    iosBundleId: 'com.example.flu2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfe-9qw00EgldtgSh2-c1GGUWs4Vz1E1U',
    appId: '1:947319131768:web:971ae5e8c4317751b3678d',
    messagingSenderId: '947319131768',
    projectId: 'suwaderm',
    authDomain: 'suwaderm.firebaseapp.com',
    storageBucket: 'suwaderm.firebasestorage.app',
    measurementId: 'G-G6Y8VQYCN1',
  );
}
